theme: jekyll-theme-slate
markdown:           redcarpet
redcarpet:
      extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "subscript", "with_toc_data"]
